workflows:
  ios-workflow:
    name: MoneyGuard iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install Expo CLI
        script: npm install -g @expo/cli
      - name: Prebuild iOS
        script: expo prebuild --platform ios --clear
      - name: Install pods
        script: cd ios && pod install
      - name: Build iOS
        script: cd ios && xcodebuild -workspace *.xcworkspace -scheme * -configuration Release -destination generic/platform=iOS -archivePath build/MoneyGuard.xcarchive archive
    artifacts:
      - ios/build/*.xcarchive
    publishing:
      email:
        recipients:
          - joelascious1@icloud.com
